import Head from 'next/head'
import { Montserrat } from 'next/font/google'
import { Header } from '@/components/Header'
import { Hero } from '@/components/Hero'
import { Footer } from '@/components/Footer'
import { AboutMusic } from '@/components/About'
import { Singers } from '@/components/Singers'
import { Pricing } from '@/components/Pricing'
import { Sponsors } from '@/components/Sponsors'
import { EventSchedule } from '@/components/EventSchedule'
import { Testimonials } from '@/components/Testimonials'
import { Gallery } from '@/components/Gallery'
import { ContactUs } from '@/components/ContactUs'

const montserrat = Montserrat({ variable: '--montserrat', subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Onebitmusic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/logoIcon.svg" />
      </Head>
      <Header />
      <main className={`${montserrat.variable} ${montserrat.className}`}>
        <Hero id="home" />
        <AboutMusic />
        <Singers />
        <EventSchedule />
        <Pricing />
        <Sponsors />
        <Testimonials />
        <Gallery />
        <ContactUs />
      </main>
      <Footer />
    </>
  )
}
